# Generated by Django 2.2.9 on 2020-01-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='이름'),
            preserve_default=False,
        ),
    ]
