# Generated by Django 2.2.9 on 2020-01-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='test2',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
