# Generated by Django 2.2.9 on 2020-01-07 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='test1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='test2',
        ),
    ]
